MOLECULE_OPENSTACK_CLIENT_IMAGE: CentOS-8-GenericCloud-8.2.2004-20200611.2.x86_64 # 8.2
MOLECULE_OPENSTACK_SERVER_IMAGE: CentOS-7-x86_64-GenericCloud-2009 # 7.9 - NB we only know 7.8 works (with 2.12.5, suspect 2.12.6 for 7.9 is always IB!)
MOLECULE_OPENSTACK_FLAVOR: optimised.v1.small
MOLECULE_OPENSTACK_NETWORK: ilab
MOLECULE_OPENSTACK_SSH_USER: centos
