# keyed off ansible_distribution_version
# see https://wiki.whamcloud.com/display/PUB/Lustre+Support+Matrix
lustre_releases:
  "7.8":
    lustre_ver: "2.12.5"
    # kernel_ver: "3.10.0-1127.19.1.el7"
    # kernel_pkg: "https://linuxsoft.cern.ch/cern/centos/7/updates/x86_64/Packages/kernel-3.10.0-1127.19.1.el7.x86_64.rpm"
    e2fsprogs: "latest"
  "7.9":
    lustre_ver: "2.12.6"
    e2fsprogs: "latest"

