# keyed off ansible_distribution_version
# see https://wiki.whamcloud.com/display/PUB/Lustre+Support+Matrix
lustre_releases:
  "7.8":
    lustre_ver: "2.12.5"
    e2fsprogs: "latest"
  "7.9":
    lustre_ver: "2.12.6"
    e2fsprogs: "latest"

