---
- name: Configure lustre server
  hosts: molecule-lustre-server
  tags:
    lustre_servers
  become: yes
  vars:
    molecule_server_disks:
      mgt: 250MB
      mdt: 250MB
      ost: 1GB
  tasks:
    - name: Configure loop devices for MGT/MDT/OST
      include_role:
        name: loopdev
      vars:
        loopdev_path: "{{ lookup('env', 'OPENSTACK_SERVER_DISK_DIR') }}/{{ item.key }}"
        loopdev_size: "{{ item.value }}"
      loop: "{{ molecule_server_disks | dict2items }}"
    - name: Find loop devices # role var registered `loopdev` is set to last result from loop so can't use that
      command:
        cmd: "losetup -j {{ lookup('env', 'OPENSTACK_SERVER_DISK_DIR') }}/{{ item }}"
      changed_when: false
      loop: "{{ molecule_server_disks.keys() }}"
      register: losetup
    # - debug:
    #     var: losetup
    - set_fact:
        molecule_server_lodevs: "{{ losetup.results | items2dict(key_name='item', value_name='stdout') }}" # value-> e.g. "/dev/loop2: [64784]:116 (/mnt/ost)"
    # - debug:
    #     var: molecule_server_lodevs
    - name: Include lustre server role
      include_role:
        name: "stackhpc.lustre.server"
      vars:
        lustre_fs_name: test_fs
        lustre_mgs_addr: "{{ hostvars['molecule-lustre-server'].ansible_default_ipv4.address }}"
        lustre_mgt: "{{ molecule_server_lodevs['mgt'].split(':')[0] }}"
        lustre_mdts: "{{ {0:molecule_server_lodevs['mdt'].split(':')[0] } }}" # see molecule_server_lodevs above for split() etc
        lustre_osts: "{{ {0:molecule_server_lodevs['ost'].split(':')[0] } }}"

- name: Configure lustre clients
  hosts: lustre_clients
  tags:
    - lustre_clients
  become: yes
  tasks:
    - include_role:
        name: "stackhpc.lustre.client"
      vars:
        lustre_fs_name: test_fs
        lustre_mgs_addr: "{{ hostvars['molecule-lustre-server'].ansible_default_ipv4.address }}"
  