- import_tasks: validate.yml

- name: validate lnet config # also defines default values for lustre_lnet_networks
  include_role:
    name: stackhpc.lustre.lnet
    tasks_from: validate.yml

- name: ensure correct kernel running
  include_role:
    name: stackhpc.kernel_packages
  vars:
    kernel_version: "{{ lustre_server_release.kernel }}"
  when: "'o2ib' in lustre_lnet_types"

# TODO: move this somewhere else??

- debug:
    msg: "{{ item }}"
  loop: "{{ lustre_lnet_networks }}"

- name: install ofed
  include_role:
    name: stackhpc.lustre.ofed
  vars:
    lustre_ofed_repofile: "{{ lustre_server_release.ofed_repo }}"
  when: "'o2ib' in lustre_lnet_types"
- name: create ifcfg
  template:
    dest: /etc/sysconfig/network-scripts/ifcfg-{{ item.interfaces[0] }}
    src: ifcfg.j2
    mode: "0644"
    owner: root
    group: root
  vars:
      lustre_ifcfg_device: "{{ item.interfaces[0] }}" # TODO: cope with multiple devices
      lustre_ifcfg_ip: "TODO" # FIXME:
      lustre_ifcfg_netmask: "TODO" # FIXME:
  loop: "{{ lustre_lnet_networks }}"
  # when: <ip adddress defined> # FIXME:
  # notify: restart network # TODO: FIXME
  
- name: enable lustre server repo
  yum_repository:
    name: lustre-server
    description: lustre-server
    file: lustre-server
    baseurl: "{{ lustre_server_release.lustre_repo }}"
    gpgcheck: no
  register: lustre_server_repo
- name: enable lustre e2fs repo
  yum_repository:
    name: e2fsprogs-wc
    description: e2fsprogs-wc
    file: e2fsprogs
    baseurl: https://downloads.whamcloud.com/public/e2fsprogs/{{ lustre_server_release.e2fsprogs}}/el{{ ansible_distribution_major_version }}/
    gpgcheck: no
  register: lustre_e2fs_repo
- name: yum-clean-metadata
  command: yum clean metadata
  args:
    warn: no
  when: lustre_server_repo.changed or lustre_e2fs_repo.changed

- name: Install Lustre Server
  yum:
    name: "lustre-{{ lustre_server_release.lustre_ver }}"
- name: Put SELinux in permissive mode, logging actions that would be blocked.
  selinux:
    policy: targeted
    state: permissive

- name: configure & start lnet
  include_role:
    name: stackhpc.lustre.lnet
  when: lustre_lnet_networks != {}

# NB might need need clients UNMOUNTED and nodemap DEACTIVATED before running this if its making changes?
# NB if you are using the default lnet (i.e. not specifically setting up lnets) then it is @tcp, not "@tcp1".
- name: Load lustre
  command: modprobe lustre
  changed_when: False
  # TODO: make persistent on boot via /etc/modules-load.d/

- import_tasks: format.yml
- import_tasks: mountpoints.yml
- import_tasks: start.yml
